---
framework: mocha
preRun:
     command:
        - npm ci
preMerge:
  pattern:
    - "./test/*.js"
postMerge:
  pattern: 
    - "./test/*.js"
postRun:
     command:
        - node --version
configFile: mocharc.yml
version: 1.0
